library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity datapath is
    port (
        clk        : in  std_logic;
        reset      : in  std_logic;

        -- Decoded in ID.  pc_src is the Branch control bit; the datapath
        -- combines it with the EX zero flag when selecting the next PC.
        pc_src      : in  std_logic;
        mem_read    : in  std_logic;
        mem_to_reg  : in  std_logic;
        mem_write   : in  std_logic;
        alu_src     : in  std_logic;
        reg_write   : in  std_logic;
        alu_control : in  std_logic_vector(3 downto 0);

        -- Inputs generated by the HDU and FU instances in riscv_core.
        pc_write    : in  std_logic;
        if_id_write : in  std_logic;
        if_id_flush : in  std_logic;
        id_ex_flush : in  std_logic;
        forward_a   : in  std_logic_vector(1 downto 0);
        forward_b   : in  std_logic_vector(1 downto 0);

        -- IF/ID instruction, provided to the control unit for decoding.
        instruction : out std_logic_vector(31 downto 0);
        -- Result of the instruction currently in EX.
        zero        : out std_logic;

        -- Pipeline state exported to the hazard and forwarding units.
        if_id_rs1_addr_o    : out std_logic_vector(4 downto 0);
        if_id_rs2_addr_o    : out std_logic_vector(4 downto 0);
        id_ex_mem_read_o    : out std_logic;
        id_ex_rd_addr_o     : out std_logic_vector(4 downto 0);
        id_ex_rs1_addr_o    : out std_logic_vector(4 downto 0);
        id_ex_rs2_addr_o    : out std_logic_vector(4 downto 0);
        ex_mem_reg_write_o  : out std_logic;
        ex_mem_mem_to_reg_o : out std_logic;
        ex_mem_rd_addr_o    : out std_logic_vector(4 downto 0);
        mem_wb_reg_write_o  : out std_logic;
        mem_wb_rd_addr_o    : out std_logic_vector(4 downto 0);
        branch_taken_o      : out std_logic
    );
end entity;

architecture structural of datapath is
    -- IF signals
    signal current_pc, pc_plus_4, next_pc : std_logic_vector(63 downto 0);
    signal instruction_fetch : std_logic_vector(31 downto 0);

    -- IF/ID signals
    signal if_id_pc_plus_4 : std_logic_vector(63 downto 0);
    signal if_id_instruction : std_logic_vector(31 downto 0);

    -- ID signals
    signal immediate_id, read_data_1_id, read_data_2_id : std_logic_vector(63 downto 0);

    -- ID/EX signals
    signal id_ex_mem_to_reg, id_ex_reg_write, id_ex_branch : std_logic;
    signal id_ex_mem_read, id_ex_mem_write, id_ex_alu_src : std_logic;
    signal id_ex_alu_control : std_logic_vector(3 downto 0);
    signal id_ex_pc_plus_4, id_ex_read_data_1, id_ex_read_data_2, id_ex_immediate : std_logic_vector(63 downto 0);
    signal id_ex_rs1_addr, id_ex_rs2_addr, id_ex_rd_addr : std_logic_vector(4 downto 0);

    -- EX signals
    signal forwarded_data_1, forwarded_data_2, alu_operand_b : std_logic_vector(63 downto 0);
    signal alu_result_ex, branch_target_ex : std_logic_vector(63 downto 0);
    signal alu_zero_ex, branch_taken : std_logic;

    -- EX/MEM signals
    signal ex_mem_mem_to_reg, ex_mem_reg_write, ex_mem_branch : std_logic;
    signal ex_mem_mem_read, ex_mem_mem_write, ex_mem_zero : std_logic;
    signal ex_mem_branch_target, ex_mem_alu_result, ex_mem_write_data : std_logic_vector(63 downto 0);
    signal ex_mem_rd_addr : std_logic_vector(4 downto 0);

    -- MEM and MEM/WB signals
    signal memory_data : std_logic_vector(63 downto 0);
    signal mem_wb_mem_to_reg, mem_wb_reg_write : std_logic;
    signal mem_wb_memory_data, mem_wb_alu_result, write_back_data : std_logic_vector(63 downto 0);
    signal mem_wb_rd_addr : std_logic_vector(4 downto 0);
begin
    -- IF: program counter, instruction memory and sequential PC.
    u_pc : entity work.pc(rtl)
        port map (
            clk => clk,
            reset => reset,
            write_en => pc_write,
            next_pc => next_pc,
            pc_out => current_pc
        );

    u_instruction_memory : entity work.instruction_memory(rtl)
        port map (
            address => current_pc,
            instruction => instruction_fetch
        );

    u_pc_adder : entity work.adder(rtl)
        port map (
            a => current_pc,
            b => x"0000000000000004",
            result => pc_plus_4
        );

    branch_taken <= id_ex_branch and alu_zero_ex;
    u_next_pc_mux : entity work.mux2(rtl)
        port map (
            input0 => pc_plus_4,
            input1 => branch_target_ex,
            sel => branch_taken,
            output => next_pc
        );

    u_if_id : entity work.if_id_register(rtl)
        port map (
            clk => clk,
            reset => reset,
            write_en => if_id_write,
            flush => if_id_flush,
            pc_plus_4_i => pc_plus_4,
            instruction_i => instruction_fetch,
            pc_plus_4_o => if_id_pc_plus_4,
            instruction_o => if_id_instruction
        );

    -- ID: asynchronous register-file reads and immediate generation use the
    -- instruction stored in IF/ID, never the instruction currently fetched.
    u_register_file : entity work.register_file(rtl)
        port map (
            clk => clk,
            write_en => mem_wb_reg_write,
            rs1_addr => if_id_instruction(19 downto 15),
            rs2_addr => if_id_instruction(24 downto 20),
            rd_addr => mem_wb_rd_addr,
            write_data => write_back_data,
            rs1_data => read_data_1_id,
            rs2_data => read_data_2_id
        );

    u_immediate_generator : entity work.immediate_generator(rtl)
        port map (
            instruction => if_id_instruction,
            immediate => immediate_id
        );

    u_id_ex : entity work.id_ex_register(rtl)
        port map (
            clk => clk,
            reset => reset,
            flush => id_ex_flush,
            mem_to_reg_i => mem_to_reg,
            reg_write_i => reg_write,
            branch_i => pc_src,
            mem_read_i => mem_read,
            mem_write_i => mem_write,
            alu_src_i => alu_src,
            alu_control_i => alu_control,
            pc_plus_4_i => if_id_pc_plus_4,
            read_data_1_i => read_data_1_id,
            read_data_2_i => read_data_2_id,
            immediate_i => immediate_id,
            rs1_addr_i => if_id_instruction(19 downto 15),
            rs2_addr_i => if_id_instruction(24 downto 20),
            rd_addr_i => if_id_instruction(11 downto 7),
            mem_to_reg_o => id_ex_mem_to_reg,
            reg_write_o => id_ex_reg_write,
            branch_o => id_ex_branch,
            mem_read_o => id_ex_mem_read,
            mem_write_o => id_ex_mem_write,
            alu_src_o => id_ex_alu_src,
            alu_control_o => id_ex_alu_control,
            pc_plus_4_o => id_ex_pc_plus_4,
            read_data_1_o => id_ex_read_data_1,
            read_data_2_o => id_ex_read_data_2,
            immediate_o => id_ex_immediate,
            rs1_addr_o => id_ex_rs1_addr,
            rs2_addr_o => id_ex_rs2_addr,
            rd_addr_o => id_ex_rd_addr
        );

    -- EX: the FU selects ID/EX, EX/MEM or MEM/WB data for each source
    -- operand.  The selected B value is also retained for store data.
    with forward_a select
        forwarded_data_1 <= id_ex_read_data_1 when "00",
                            write_back_data   when "01",
                            ex_mem_alu_result when "10",
                            id_ex_read_data_1 when others;

    with forward_b select
        forwarded_data_2 <= id_ex_read_data_2 when "00",
                            write_back_data   when "01",
                            ex_mem_alu_result when "10",
                            id_ex_read_data_2 when others;

    u_alu_operand_mux : entity work.mux2(rtl)
        port map (
            input0 => forwarded_data_2,
            input1 => id_ex_immediate,
            sel => id_ex_alu_src,
            output => alu_operand_b
        );

    u_alu : entity work.alu(rtl)
        port map (
            a => forwarded_data_1,
            b => alu_operand_b,
            alu_control => id_ex_alu_control,
            result => alu_result_ex,
            zero => alu_zero_ex
        );

    -- ID/EX carries PC+4, so subtract four before applying the displacement.
    branch_target_ex <= std_logic_vector(signed(id_ex_pc_plus_4) + signed(id_ex_immediate) - to_signed(4, 64));

    u_ex_mem : entity work.ex_mem_register(rtl)
        port map (
            clk => clk,
            reset => reset,
            mem_to_reg_i => id_ex_mem_to_reg,
            reg_write_i => id_ex_reg_write,
            branch_i => id_ex_branch,
            mem_read_i => id_ex_mem_read,
            mem_write_i => id_ex_mem_write,
            zero_i => alu_zero_ex,
            branch_target_i => branch_target_ex,
            alu_result_i => alu_result_ex,
            write_data_i => forwarded_data_2,
            rd_addr_i => id_ex_rd_addr,
            mem_to_reg_o => ex_mem_mem_to_reg,
            reg_write_o => ex_mem_reg_write,
            branch_o => ex_mem_branch,
            mem_read_o => ex_mem_mem_read,
            mem_write_o => ex_mem_mem_write,
            zero_o => ex_mem_zero,
            branch_target_o => ex_mem_branch_target,
            alu_result_o => ex_mem_alu_result,
            write_data_o => ex_mem_write_data,
            rd_addr_o => ex_mem_rd_addr
        );

    -- MEM and WB.
    u_data_memory : entity work.data_memory(rtl)
        port map (
            clk => clk,
            mem_read => ex_mem_mem_read,
            mem_write => ex_mem_mem_write,
            address => ex_mem_alu_result,
            write_data => ex_mem_write_data,
            read_data => memory_data
        );

    u_mem_wb : entity work.mem_wb_register(rtl)
        port map (
            clk => clk,
            reset => reset,
            mem_to_reg_i => ex_mem_mem_to_reg,
            reg_write_i => ex_mem_reg_write,
            memory_data_i => memory_data,
            alu_result_i => ex_mem_alu_result,
            rd_addr_i => ex_mem_rd_addr,
            mem_to_reg_o => mem_wb_mem_to_reg,
            reg_write_o => mem_wb_reg_write,
            memory_data_o => mem_wb_memory_data,
            alu_result_o => mem_wb_alu_result,
            rd_addr_o => mem_wb_rd_addr
        );

    u_write_back_mux : entity work.mux2(rtl)
        port map (
            input0 => mem_wb_alu_result,
            input1 => mem_wb_memory_data,
            sel => mem_wb_mem_to_reg,
            output => write_back_data
        );

    instruction <= if_id_instruction;
    zero <= alu_zero_ex;
    if_id_rs1_addr_o <= if_id_instruction(19 downto 15);
    if_id_rs2_addr_o <= if_id_instruction(24 downto 20);
    id_ex_mem_read_o <= id_ex_mem_read;
    id_ex_rd_addr_o <= id_ex_rd_addr;
    id_ex_rs1_addr_o <= id_ex_rs1_addr;
    id_ex_rs2_addr_o <= id_ex_rs2_addr;
    ex_mem_reg_write_o <= ex_mem_reg_write;
    ex_mem_mem_to_reg_o <= ex_mem_mem_to_reg;
    ex_mem_rd_addr_o <= ex_mem_rd_addr;
    mem_wb_reg_write_o <= mem_wb_reg_write;
    mem_wb_rd_addr_o <= mem_wb_rd_addr;
    branch_taken_o <= branch_taken;
end architecture;
